#
# txtai Material for MkDocs configuration
#

site_name: txtai
site_description: "txtai: Build AI-powered semantic search applications"
repo_name: neuml/txtai
repo_url: https://github.com/neuml/txtai
copyright: Â© NeuML LLC, Apache-2.0 License
theme:
    name: material
    logo: images/logo.png
    favicon: images/logo.png
    custom_dir: docs/overrides
    icon:
        repo: fontawesome/brands/github
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.instant
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                rendering:
                    show_root_full_path: false
                    show_root_heading: true
                    show_root_toc_entry: false
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
nav:
    - Home: index.md
    - Why txtai?: why.md
    - Installation: install.md
    - Examples: examples.md
    - Embeddings:
        - embeddings/index.md
        - Configuration:
            - embeddings/configuration/index.md
            - Cloud: embeddings/configuration/cloud.md
        - Index Guide: embeddings/indexing.md
        - Methods: embeddings/methods.md
        - Query Guide: embeddings/query.md
    - Pipeline:
        - pipeline/index.md
        - Audio:
            - Text To Speech: pipeline/audio/texttospeech.md
            - Transcription: pipeline/audio/transcription.md
        - Data:
            - Segmentation: pipeline/data/segmentation.md
            - Tabular: pipeline/data/tabular.md
            - Textractor: pipeline/data/textractor.md
        - Image:
            - Caption: pipeline/image/caption.md
            - Image Hash: pipeline/image/imagehash.md
            - Objects: pipeline/image/objects.md
        - Text:
            - Entity: pipeline/text/entity.md
            - Extractor: pipeline/text/extractor.md
            - Generator: pipeline/text/generator.md
            - Labels: pipeline/text/labels.md
            - Sequences: pipeline/text/sequences.md
            - Similarity: pipeline/text/similarity.md
            - Summary: pipeline/text/summary.md
            - Translation: pipeline/text/translation.md
        - Train:
            - HF ONNX: pipeline/train/hfonnx.md
            - ML ONNX: pipeline/train/mlonnx.md
            - Trainer: pipeline/train/trainer.md
    - Workflow:
        - workflow/index.md
        - Schedule: workflow/schedule.md
        - Tasks:
            - workflow/task/index.md
            - Console: workflow/task/console.md
            - Export: workflow/task/export.md
            - File: workflow/task/file.md
            - Image: workflow/task/image.md
            - Retrieve: workflow/task/retrieve.md
            - Service: workflow/task/service.md
            - Storage: workflow/task/storage.md
            - Template: workflow/task/template.md
            - Url: workflow/task/url.md
            - Workflow: workflow/task/workflow.md
    - API:
        - api/index.md
        - Cluster: api/cluster.md
        - Configuration: api/configuration.md
        - Methods: api/methods.md
    - Cloud: cloud.md
    - FAQ: faq.md
    - Further Reading: further.md
