# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
        if: matrix.os != "windows-latest"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
        if: matrix.os == "windows-latest"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies - Linux
        run: sudo apt-get install libsndfile1
        if: matrix.os == 'ubuntu-latest'

      - name: Install dependencies - MacOS
        run: brew install libomp
        if: matrix.os == 'macos-latest'

      - name: Install dependencies - Windows
        run: choco install wget
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U pip wheel coverage coveralls
          pip install .
          python -c "import nltk; nltk.download('punkt')"
          python --version
          make data coverage

      - uses: pre-commit/action@v2.0.0
        if: matrix.os == 'ubuntu-latest'

      - name: Test Coverage
        run: coveralls --service=github
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
